hmcts/et-wa-task-configuration

build.gradle, src/main/resources/wa-task-initiation-et-vetting.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/ETTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2761
Add Unit Test for new DMN
```
[ ] Yes
[x ] No
```
=> Unit Test for ET Vetting

README.md, bin/env_variables_all.txt, scripts/camunda-deployment.sh, scripts/idam-service-token.sh, src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.bpmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn
=> RET-2760: Added scripts for importing DMNs/BPMNs to Camunda

Jenkinsfile_CNP, config/owasp/suppressions.xml
=> suppressed CVEs and corrected tenant/product id

Jenkinsfile_CNP
=> Changed product/tenent ID to upper cases

Jenkinsfile_CNP
=> changed product to et

src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/ETTaskInitiationTest.java
=> Fixed checkstyle and test

charts/et-task-configuration/values.yaml
Updated Image name in chart.yaml
```
[ ] Yes
[x] No
```
=> Update Charts values.yaml

build.gradle, config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTest.java
=> RET-2376 Et3Processing

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2435
```
[ ] Yes
[ x] No
```
=> RET-2435 added IssueInitialConsiderationDirections

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/RET-2436
https://tools.hmcts.net/jira/browse/RET-2437
```
[ ] Yes
[ ] No
```
=> RET-2436, RET-2437 IssueInitialConsiderationDirections

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2347
https://tools.hmcts.net/jira/browse/RET-2348
https://tools.hmcts.net/jira/browse/RET-2349
Create Task "ReviewReferralAdmin" for Admin
Complete "ReviewReferralAdmin" Task for Admin
Cancel "ReviewReferralAdmin" Task for Admin
```
[ ] Yes
[x] No
```
=> Ret 2347 - Create Task "ReviewReferralAdmin" for Admin

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2379
https://tools.hmcts.net/jira/browse/RET-2380
https://tools.hmcts.net/jira/browse/RET-2381
This story deals with the automated creation of "ReviewReferralResponseAdmin" task following a referral event
```
[ ] Yes
[x] No
```
=> RET-2379-ReviewReferralResponseAdmin

build.gradle, charts/et-wa-task-configuration/Chart.yaml, charts/et-wa-task-configuration/values.preview.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RET-3720
Use wa-chart to deploy ET WA to Preview
```
[ ] Yes
[x] No
```
=> RET-3720: WA Preview

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2450
https://tools.hmcts.net/jira/browse/RET-2451
This story deals with auto creation of the "IssueJudgment" task following referral from a Judge 
```
[ ] Yes
[x] No
```
=> RET-2450-IssueJudgment

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn
https://tools.hmcts.net/jira/browse/RET-3720
Simplify CaseName for testing purposes
```
[ ] Yes
[ ] No
```
=> RET-3720-Test: SimplifyCaseName

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn
https://tools.hmcts.net/jira/browse/RET-3720
Simplify for testing
```
[ ] Yes
[x] No
```
=> RET-3720-Test: SimplyForTest

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTest.java
https://tools.hmcts.net/jira/browse/RET-3188
https://tools.hmcts.net/jira/browse/RET-3189
https://tools.hmcts.net/jira/browse/RET-3190
```
[ ] Yes
[ ] No
```
=> Ret 3188 contact tribunal withan application

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn
https://tools.hmcts.net/jira/browse/RET-3828
Restore caseName and isUrgent. 
To be worked on separately to DTSPO-14167
```
[ ] Yes
[x] No
```
=> RET-3828: Undo caseData simplification

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RET-3833
Check Dependencies
```
[ ] Yes
[x] No
```
=> RET-3833: Update CVEs

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RET-2514
```
[ ] Yes
[ ] No
```
=> RET-2849-accessRequest change

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RET-3828
Fix CaseName issue with Camunda couldn't parse Respondent Name
```
[ ] Yes
[x] No
```
=> RET-3828: Fix Case Name issue due to outdated Camunda

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-3851
Fix typo (Hearings) and duplicate issue (Rule 21)
Replace Working Days Allowed with dueDateIntervalDays
```
[ ] Yes
[x] No
```
=> RET 3851 - Due Date fixes

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTest.java
https://tools.hmcts.net/jira/browse/RET-2501
SUBMIT_CLAIMANT_TSE & respondentTSE done
```
[ ] Yes
[x] No
```
=> RET 2501 Create "AmendPartyDetails" Task for Admin

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-2501
https://tools.hmcts.net/jira/browse/RET-2502
https://tools.hmcts.net/jira/browse/RET-2503
Callbacks is deleting all the old values, so now using the values where the rest in caseData
```
[ ] Yes
[x] No
```
=> RET 2501: Amend party details responses

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RET-3180
```
[ ] Yes
[ ] No
```
=> Ret 3180 task reconfigure

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn
https://tools.hmcts.net/jira/browse/RET-4056
Typo - query missing ()
```
[ ] Yes
[x] No
```
=> RET-4056: Fix Typo

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RET-4056
Remove State consideration from Referral Tasks
```
[ ] Yes
[x] No
```
=> RET-4056: Remove PostEventState from Referrals

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTest.java
https://tools.hmcts.net/jira/browse/RET-4096
```
[ ] Yes
[ ] No
```
=> RET-4096 cancel dmn updated

src/main/resources/wa-task-cancellation-employment-et_scotland.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn
https://tools.hmcts.net/jira/browse/RET-4124
Added Scotland DMNs
```
[ ] Yes
[x] No
```
=> RET-4124: Add Scottish DMNs

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-cancellation-employment-et_scotland.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-4124
Add Unit Tests for Scottish DMNs
```
[ ] Yes
[x] No
```
=> RET-4124: Add Scottish DMN Tests

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RET-4120
```
[ ] Yes
[ ] No
```
=> RET-4120 navigation url updated

src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4120
```
[ ] Yes
[ ] No
```
=> RET-4120 desc url updated in scotland dmn file

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTest.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java
https://tools.hmcts.net/jira/browse/RET-4095
Update Completion DMNs
```
[ ] Yes
[x] No
```
=> RET-4095: Update Completion DMNs

build.gradle, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4095
Some updates for Completion found in testing
```
[ ] Yes
[x] No
```
=> RET-4095: Completion updates

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4095
Fix Task Next Step
```
[ ] Yes
[x] No
```
=> RET-4095: Update ListServeClaim config

src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java
n/a
Remove own Task Supervisor
```
[ ] Yes
[x] No
```
=> Ret 0000- Remove own

.github/renovate.json, charts/et-wa-task-configuration/Chart.yaml, renovate.json, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4158
Add Region, Location and Case Management Category to Config DMN
```
[ ] Yes
[x] No
```
=> RET-4158: Add Region, Location and Case Management Category to Config

build.gradle, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4004
Camunda Updates
```
[ ] Yes
[x] No
```
=> RET-4004 WA enablers

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4004
Camunda Updates
```
[ ] Yes
[x] No
```
=> RET-4004: Smoke Test on Preview

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-4244
Split amend party details so that completion could distinguish which task to close
```
[ ] Yes
[x] No
```
=> RET-4244 Split AmendPartyDetails

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4376
Update Description/Next Steps
```
[x] Yes
[ ] No
```
=> RET 4376: Update Description/Next Steps

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-2432
Create "CompleteInitialConsideration" Task for Judge
```
[ ] Yes
[x] No
```
=> RET-2432-CompleteInitialConsideration-task-ccd-changes

src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCompletionTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-4014
Use caseData 
```
[ ] Yes
[x] No
```
=> RET-4014: List A Hearing DMN update

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java
https://tools.hmcts.net/jira/browse/RET-4016
https://tools.hmcts.net/jira/browse/RET-2435
Connect up RET-4016 & RET-2435
=> RET-4016: Connect up RET-4016 & RET-2435

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4516
Change triggering event for Et3Processing
=> RET-4516: Change triggering event for Et3Processing

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4517
Add additional triggering event for Et3Processing
=> RET-4517: Add triggering event for Et3Processing

build.gradle, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-3296
```
[ ] Yes
[ ] No
```
=> changed event name for Rule21Referral and removed delay condition

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-3180
Add CanReconfigure to LocationName and nextHearingDate.
```
[ ] Yes
[x] No
```
=> RET-3180: Update CanReconfigure

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4716
removed rule26 Yes as a requirement for initial consideration
```
[] Yes
[x] No
```
=> RET-4716: removed rule26 Yes as a requirement for initial consideration

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-cancellation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskCancellationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4718
Reconfigure on caseTransferSameCountry
```
[] Yes
[x] No
```
=> RET-4718: Reconfigure on caseTransferSameCountry

scripts/camunda-deployment.sh
https://tools.hmcts.net/jira/browse/RET-3564
Updated the script to upload BPMN files to Demo environment
```
[ ] Yes
[ ] No
```
=> RET-3564  Updated the script to upload BPMN files to Demo environment

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4747
Referral Tasks now consider nextHearingDate
```
[] Yes
[x] No
```
=> RET-4747: Referral Tasks now consider nextHearingDate

src/main/resources/wa-task-initiation-ia-asylum.bpmn
https://tools.hmcts.net/jira/browse/RET-3564
Move bpmn to resources to be picked up by demo pipeline
```
[] Yes
[x] No
```
=> RET-3564: Move bpmn to resources to be picked up by demo pipeline

src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java
https://tools.hmcts.net/jira/browse/RET-4741
```
[ ] Yes
[ ] No
```
=> Ret 4741 - Assign task permissions to caseworkers and judges

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4718
Added Reconfigure on Region for EW/SC
```
[] Yes
[x] No
```
=> RET-4718: Added Reconfigure on Region for EW/SC

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn
n/a
Merge with Master was incomplete.
```
[ ] Yes
[x] No
```
=> RET-0000: MergeFix

src/main/resources/wa-task-cancellation-employment-et_englandwales.dmn, src/main/resources/wa-task-cancellation-employment-et_scotland.dmn, src/main/resources/wa-task-completion-employment-et_englandwales.dmn, src/main/resources/wa-task-completion-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4752
IssueJudgement Task is only triggered when Draft And Sign Judgement IS a Judgement
```
[ ] Yes
[x] No
```
=> RET-4752: IssueJudgement Task is only triggered by Judgement

src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java
https://tools.hmcts.net/jira/browse/RET-4838
Add Lead Judge as a Case Role
```
[ ] Yes
[x] No
```
=> RET-4838: Add Lead Judge as Case Role

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4861
Change wording on IssueJudgement
```
[ ] Yes
[x] No
```
=> RET-4861: Change wording on IssueJudgement

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4866
Issue with Referral reconfiguration.
```
[ ] Yes
[x] No
```
=> RET-4866: ReferralCollection breaks Reconfigure

scripts/camunda-deployment.sh, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-4864
Make Application Tasks have a Dynamic Task Name
Also a refactor of how Referral Names are created
```
[ ] Yes
[x] No
```
=> RET-4864: Dynamic Task Name for Applications

src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-4933
Add Rule 21 to Task Types
```
[ ] Yes
[x] No
```
=> RET-4933: Add Rule 21 to Task Types

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-5038
Add ECC condition
```
[ ] Yes
[ ] No
```
=> RET-5038 - Add ECC condition

src/main/resources/wa-task-completion-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-completion-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-initiation-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-permissions-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-types-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-types-employment-et_scotland_multiple.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCompletionMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCompletionMultipleTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskConfigurationMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskConfigurationMultipleTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskInitiationMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskInitiationMultipleTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskPermissionsMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskPermissionsMultipleTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskTypeMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskTypeMultipleTestScot.java
https://tools.hmcts.net/jira/browse/RET-5140
Create Task "MultiplesReviewReferralResponseAdmin" for Admin (MUL WA)
```
[ ] Yes
[ ] No
```
=> RET-5140-V2

src/main/resources/wa-task-cancellation-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-cancellation-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_scotland_multiple.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCancellationMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCancellationMultipleTestScot.java
https://tools.hmcts.net/jira/browse/RET-5258
disposeCase doesn't exist on Multiples. Use close instead
```
[ ] Yes
[x] No
```
=> RET-5258: disposeCase doesn't exist on Multiples. Use close instead

src/main/resources/wa-task-cancellation-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-cancellation-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-completion-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-completion-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-initiation-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/main/resources/wa-task-permissions-employment-et_scotland_multiple.dmn, src/main/resources/wa-task-types-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-types-employment-et_scotland_multiple.dmn
https://tools.hmcts.net/jira/browse/RET-5258
Manual tidy  up of DMNs
```
[ ] Yes
[x] No
```
=> RET-5258: Tidy Up of DMNs.

src/main/resources/wa-task-completion-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-completion-employment-et_scotland_multiple.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCompletionMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskCompletionMultipleTestScot.java
https://tools.hmcts.net/jira/browse/RET-5258
Add Empty row to Completion DMNs
```
[ ] Yes
[x] No
```
=> RET-5258: Add Empty row to Completion DMNs

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java
https://tools.hmcts.net/jira/browse/RET-5316
Revert Referrals tab on task
```
[ ] Yes
[x] No
```
=> RET-5316 - Revert Referrals tab on task

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn
https://tools.hmcts.net/jira/browse/RET-5317
Create a task regardless of state on Application based events
```
[ ] Yes
[X] No
```
=> Remove state from Application based events

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/utility/InitiationUtility.java
A "do not list" option added for hearings
https://tools.hmcts.net/jira/browse/RET-5221
```
[ ] Yes
[ x] No
```
=> do not list option added for hearings

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
=> claimant rep app

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/utility/InitiationUtility.java
https://tools.hmcts.net/jira/browse/RET-5221
initialConsideration event create initial Consideration directions task
```
[ ] Yes
[ x ] No
```
=> correction on the task created added

src/main/resources/wa-task-permissions-employment-et_englandwales.dmn, src/main/resources/wa-task-permissions-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskPermissionsTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/utility/PermissionsUtility.java
=> FeePaidJudge

build.gradle, config/owasp/suppressions.xml, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
Create ET3 Processing task when a respondent submits in an ET3
```
[ ] Yes
[ ] No
```
=> ET3 Lip submission to start ET3 Processing

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
=> Update to event name

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/utility/InitiationUtility.java
=> IC Updates

src/main/resources/privilege-calendar-engwales.json, src/main/resources/privilege-calendar-scotland.json, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_englandwales_multiple.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-configuration-employment-et_scotland_multiple.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskConfigurationMultipleTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/multiples/EmploymentTaskConfigurationMultipleTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/utility/ConfigurationUtility.java
- Configure Christmas holidays for 2024
- Added ET configuration for days off for EngWales and Scotland
```
[ ] Yes
[ ] No
```
=> Holiday updates

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-5539
Updated task name
```
[ ] Yes
[ ] No
```
=> Update task name

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
Reverts hmcts/et-wa-task-configuration#317
=> Revert "Update task name"

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-5539
Update Rule 21 to Rule 22 
```
[ ] Yes
[ ] No
```
=> Update Rule 21 to Rule 22

build.gradle, config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn
- [x ] commit messages are meaningful and follow good commit message guidelines
referralreplyCollection null bug fix
```
[ ] Yes
[x] No
```
=> Prod referral bug fix br

src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java
https://tools.hmcts.net/jira/browse/RET-5307
Add 'initiateCase' rule to DMN files and update test cases
```
[ ] Yes
[ ] No
```
=> Add 'initiateCase' rule to DMN files and update test cases

src/main/resources/wa-task-configuration-employment-et_englandwales.dmn, src/main/resources/wa-task-configuration-employment-et_scotland.dmn, src/main/resources/wa-task-initiation-employment-et_englandwales.dmn, src/main/resources/wa-task-initiation-employment-et_scotland.dmn, src/main/resources/wa-task-types-employment-et_englandwales.dmn, src/main/resources/wa-task-types-employment-et_scotland.dmn, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskConfigurationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskInitiationTestScot.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestEW.java, src/test/java/uk/gov/hmcts/et/taskconfiguration/dmn/EmploymentTaskTypeTestScot.java
https://tools.hmcts.net/jira/browse/RET-5989
* rename 'Review ECC Response' to 'Review ECC Reply'
* next steps to be ET3 processing for 'Review ECC Reply'
```
[ ] Yes
[x ] No
```
=> Review ECC Reply

src/main/resources/privilege-calendar-engwales.json, src/main/resources/privilege-calendar-scotland.json
=> Fix date for Fixed Christmas Privilege Day 2025 in privilege calendars
